CREATE TABLE users (
	id BINARY(16) PRIMARY KEY NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	username VARCHAR(30) UNIQUE NOT NULL,
	name VARCHAR(30) NOT NULL,
	profile_photo VARCHAR(200) NULL,
	birth_date DATE NOT NULL,
	description VARCHAR(200) NULL,
	password VARCHAR(200) NOT NULL,
	is_pro_account BOOLEAN NOT NULL,
	is_active BOOLEAN NULL,
	created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_date DATETIME DEFAULT CURRENT_TIMESTAMP NULL,
	status ENUM('ACTIVE', 'PASSIVE', 'SUSPENDED') DEFAULT 'ACTIVE' NOT NULL
);