CREATE TABLE tweets (
	id BINARY(16) PRIMARY KEY NOT NULL,
	text VARCHAR(280) NOT NULL,
	voice_path VARCHAR(200) NULL,
	created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_date DATETIME DEFAULT CURRENT_TIMESTAMP NULL
);