CREATE TABLE users (
	id BINARY(16) PRIMARY KEY NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	username VARCHAR(30) UNIQUE NOT NULL,
	name VARCHAR(30) NOT NULL,
	profile_photo VARCHAR(200) NULL,
	birth_date DATE NOT NULL,
	description VARCHAR(200) NULL,
	password VARCHAR(200) NOT NULL,
	is_pro_account BOOLEAN NOT NULL DEFAULT false,
	is_private BOOLEAN NOT NULL DEFAULT false,
	created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted_date DATETIME NULL,
	status ENUM('ACTIVE', 'PASSIVE', 'SUSPENDED', 'UNCONFIRMED', 'BLOCKED') DEFAULT 'UNCONFIRMED' NOT NULL
);